spring.application.name=Gym_Shop_2026
spring.security.user.name=admin_778$
spring.security.user.password=Ic3Land_778$

# Database info
database.server=gymshop-db.c1oue0a621xu.eu-west-1.rds.amazonaws.com:3306
database.username=caloscareoghan
database.password=Iceland_778$
database.db=gymshopdb

#Thymeleaf Settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#webhook (might need to change on every machine, if so, create branching for each one of us)
stripe.webhook.secret=whsec_240e9a751b6b537ac31fb12cd9af0953f9e02071f93cd95ed5eca017bcb7c8ad

#Stripe keys
stripe.api.key=sk_test_51TNL8dGnoXtKQ2PxB5RqdbfD7VTu7rMbwCw86U4Ii0UGZ2bdpIwmlBKRF4X122fnsLp7R16w320hBWbgSjkadNN800qflddwWm
stripe.api.publishableKey=pk_test_51TNL8dGnoXtKQ2Pxz0912QSuPECaWZ9DxGDr57GrosRb7bcG39kTP51OFzrwOXChVj0a1BRJaxBEMRkaj4EslagC00Ej6gLYeH

logging.level.org.springframework.security=DEBUG
